---
# tasks file for Ubuntu1804-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Ubuntu 18.04. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - not ansible_distribution == "Ubuntu"
      - not ansible_distribution_release == "bionic"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include: pre.yml
  become: true

- include: azure.yml
  become: true